// export const FETCH_BURGERS = "FETCH_BURGERS";
export const BURGERS_IS_LOADING = "BURGERS_IS_LOADING";
export const BURGERS_HAS_ERRORED = "BURGERS_HAS_ERRORED";
export const FETCH_BURGERS_SUCCESS = "FETCH_BURGERS_SUCCESS";

// export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";
// export const FETCH_INGREDIENT = "FETCH_INGREDIENT";
export const INGREDIENTS_IS_LOADING = "INGREDIENTS_IS_LOADING";
export const INGREDIENTS_HAS_ERRORED = "INGREDIENTS_HAS_ERRORED";
export const FETCH_INGREDIENTS_SUCCESS = "FETCH_INGREDIENTS_SUCCESS";
export const FETCH_INGREDIENT_SUCCESS = "FETCH_INGREDIENT_SUCCESS";

